### ISSUE TITLE
乘票人是自动获取全部的？联系人里的全部给下单吗？

### ISSUE THREAD

**Issue by espen7** [kalvinGit/J12306#13]
乘票人是自动获取全部的？联系人里的全部给下单吗？

**Comment by kalvinGit** [comment]
不是，购票人就是当前账号的用户本人

**Comment by espen7** [comment]
是只能用户本人下单是吧？其他联系人可以下单吗

**Comment by kalvinGit** [comment]
是的，目前只能对用户本人下单。如果你需要为其它人抢票，可用在main方法里面使用多线程分别登录多个用户一起抢票
