### ISSUE TITLE
登录失败了

### ISSUE THREAD

**Issue by youyinluo** [kalvinGit/J12306#2]
登录失败，可能需要设置RAIL_EXPIRATION cookie值
![{E4C75DA8-2796-4F23-BBF5-3C637D01C60D} png](https://user-images.githubusercontent.com/49855068/70910311-7329a800-204a-11ea-8baf-8f4ebc49e948.jpg)

**Comment by kalvinGit** [comment]
这个问题已经解决了，接口【https://kyfw.12306.cn/otn/HttpZF/logdevice】的参数已失效需要更新一下就好；请在github上拉取最新源代码运行即可

**Comment by youyinluo** [comment]
![image](https://user-images.githubusercontent.com/49855068/70996112-1642f600-210d-11ea-81c2-f619c7c35356.png)
你好大哥，我看这个候补也用不了

**Comment by youyinluo** [comment]
![image](https://user-images.githubusercontent.com/49855068/70996589-0d9eef80-210e-11ea-9e46-161cea36cbdc.png)

你好大哥，我看这个候补也用不了

**Comment by youyinluo** [comment]
![image](https://user-images.githubusercontent.com/49855068/70996771-72f2e080-210e-11ea-9eb1-484e2f333bbc.png)
没票的情况下发生了这样的事情

**Comment by youyinluo** [comment]
> ![图片](https://user-images.githubusercontent.com/49855068/70996771-72f2e080-210e-11ea-9eb1-484e2f333bbc.png)
> 没票的情况下发生了这样的事情

这是因为我改了刷票速度，改回来就可以了

**Comment by kalvinGit** [comment]
刷票速度（单位秒）只能配置正整数，不能用小数的
