### ISSUE TITLE
车席类型枚举有误

### ISSUE THREAD

**Issue by ishbn** [kalvinGit/J12306#20]
1. 问题1：
路径：\src\com\kalvin\J12306\config\TicketSeatType.java
枚举无座的key有误,应该为N。

1. 问题2:
路径：\src\com\kalvin\J12306\Go12306.java
是否如注释所说，只支持三种选择：一等座、二等座、无座。在Main.class上配置其他类型的席位是否可以？

![搜狗截图20200101232205](https://user-images.githubusercontent.com/39191841/71642918-9ceefa00-2ced-11ea-9b21-712f9f9aa980.png)

**Comment by kalvinGit** [comment]
1.枚举key是正确的，【N】只是本程序用来代表无座的标识，提交订单的无座标识和二等座是一样的都是【O】。
2.可以配置其它席位，Go12306.java这个类的注释是旧的，没有更新；请以Main.java里面的注释为准。
