### ISSUE TITLE
302

### ISSUE THREAD

**Issue by anquandianya** [kalvinGit/J12306#26]
老哥代码还能用不  我的打开就出现302 接口不对

**Comment by kalvinGit** [comment]
你在配置文件那里更新一下查票接口吧，官网经常更新接口的

**Comment by anquandianya** [comment]
谢谢老哥！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kalvinGit"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午10:18
收件人:&nbsp;"kalvinGit/J12306"<J12306@noreply.github.com&gt;;
抄送:&nbsp;"青春猪头少年"<564364920@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kalvinGit/J12306] 302 (#26)





 
你在配置文件那里更新一下查票接口吧，官网经常更新接口的
