### ISSUE TITLE
不知道为什么前天还可以查询，今天就不行了

### ISSUE THREAD

**Issue by youyinluo** [kalvinGit/J12306#8]
![image](https://user-images.githubusercontent.com/49855068/71317085-33354b80-24b6-11ea-909f-412ac88443e9.png)
你们又遇到这种情况吗？我的填写的信息
![image](https://user-images.githubusercontent.com/49855068/71317109-99ba6980-24b6-11ea-990e-b1b43e7bcb83.png)

**Comment by kalvinGit** [comment]
官方查票接口变了。（重新拉下代码就可以了）

**Comment by youyinluo** [comment]
查票接口，对你来说有难度吗
